<!-- switcher-grid and list alignment -->
<!-- //switcher-grid and list alignment -->
<!-- breadcrumbs -->
<div class="w3layouts-breadcrumbs text-center">
    <div class="container">
			<span class="agile-breadcrumbs">
			<a href="<?= $this->url('home')?>"><i class="fa fa-home home_1"></i></a> /
			<a href="<?= $this->url('ads.list')?>">All Ads</a>
            <?php if ($this->query['category'] ?? ''):?>
			     / <span><?= $this->t(\App\Constants::categoryName($this->query['category']))?></span>
            <?php endif;?>
            </span>
    </div>
</div>
<!-- //breadcrumbs -->
<!-- Products -->
<div class="total-ads main-grid-border">
    <div class="container">
        <div class="select-box"></div>
        <div class="all-categories">
            <h3> <?= $this->translate('Select your category and find the perfect ad')?></h3>
            <ul class="all-cat-list">
                <?php foreach (\App\Constants::getCategoriesDescriptions() as $slug => $description):?>
                    <li><a
                        href="<?= $this->url('ads.list', [], ['category' => $slug])?>"
                        <?= (($this->query['category'] ?? '') === $slug) ? ' style="font-weight:700;"' : ''?>
                        ><?= $this->translate($description)?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>
                <?php endforeach;?>

                <li><a href="<?= $this->url('ads.list', [], ['category' => '1-ano'])?>"><?= $this->t('Children Education')?> - <?= $this->t('1st Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>

                <li><a href="<?= $this->url('ads.list', [], ['category' => '2-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_FUNDAMENTAL_I))?> - <?= $this->t('2nd Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>
                <li><a href="<?= $this->url('ads.list', [], ['category' => '3-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_FUNDAMENTAL_I))?> - <?= $this->t('3rd Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>
                <li><a href="<?= $this->url('ads.list', [], ['category' => '4-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_FUNDAMENTAL_I))?> - <?= $this->t('4th Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>
                <li><a href="<?= $this->url('ads.list', [], ['category' => '5-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_FUNDAMENTAL_I))?> - <?= $this->t('5th Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>

                <li><a href="<?= $this->url('ads.list', [], ['category' => '6-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_FUNDAMENTAL_II))?> - <?= $this->t('6th Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>
                <li><a href="<?= $this->url('ads.list', [], ['category' => '7-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_FUNDAMENTAL_II))?> - <?= $this->t('7th Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>
                <li><a href="<?= $this->url('ads.list', [], ['category' => '8-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_FUNDAMENTAL_II))?> - <?= $this->t('8th Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>
                <li><a href="<?= $this->url('ads.list', [], ['category' => '9-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_FUNDAMENTAL_II))?> - <?= $this->t('9th Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>

                <li><a href="<?= $this->url('ads.list', [], ['category' => 'em-1-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> - <?= $this->t('1st Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>
                <li><a href="<?= $this->url('ads.list', [], ['category' => 'em-2-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> - <?= $this->t('2nd Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>
                <li><a href="<?= $this->url('ads.list', [], ['category' => 'em-3-ano'])?>"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> - <?= $this->t('3rd Year')?> <span class="num-of-ads">(<?= mt_rand(100, 5000)?>)</span></a></li>
            </ul>
        </div>
        <div class="ads-grid">
            <div class="side-bar col-md-3">
                <div class="search-hotel">
                    <h3 class="agileits-sear-head"><?= $this->t('Name contains')?></h3>
                    <form>
                        <input type="text" value="<?= $this->t('Product name...')?>" onfocus="this.value = '';"
                               onblur="if (this.value == '') {this.value = '<?= $this->t('Product name...')?>';}" required="">
                        <input type="submit" value=" ">
                    </form>
                </div>

                <div class="range">
                    <h3 class="agileits-sear-head"><?= $this->t('Price range')?></h3>
                    <ul class="dropdown-menu6">
                        <li>

                            <div id="slider-range"></div>
                            <input type="text" id="amount" style="border: 0; color: #ffffff; font-weight: normal;"/>
                        </li>
                    </ul>
                </div>
                <div class="w3ls-featured-ads">
                    <h2 class="sear-head fer"><?= $this->t('Featured Ads')?></h2>
                    <div class="w3l-featured-ad">
                        <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                            <div class="w3-featured-ad-left">
                                <img src="/images/f1.jpg" title="ad image" alt=""/>
                            </div>
                            <div class="w3-featured-ad-right">
                                <h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
                                <p>R$ 450</p>
                            </div>
                            <div class="clearfix"></div>
                        </a>
                    </div>
                    <div class="w3l-featured-ad">
                        <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                            <div class="w3-featured-ad-left">
                                <img src="/images/f2.jpg" title="ad image" alt=""/>
                            </div>
                            <div class="w3-featured-ad-right">
                                <h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
                                <p>R$ 380</p>
                            </div>
                            <div class="clearfix"></div>
                        </a>
                    </div>
                    <div class="w3l-featured-ad">
                        <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                            <div class="w3-featured-ad-left">
                                <img src="/images/f3.jpg" title="ad image" alt=""/>
                            </div>
                            <div class="w3-featured-ad-right">
                                <h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
                                <p>R$ 560</p>
                            </div>
                            <div class="clearfix"></div>
                        </a>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="agileinfo-ads-display col-md-9">
                <div class="wrapper">
                    <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
                        <ul id="myTab" class="nav nav-tabs nav-tabs-responsive" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home"
                                   aria-expanded="true">
                                    <span class="text"><?= $this->t('All Ads')?></span>
                                </a>
                            </li>
                            <li role="presentation" class="next">
                                <a href="#profile" role="tab" id="profile-tab" data-toggle="tab"
                                   aria-controls="profile">
                                    <span class="text"><?= $this->t('Ads with Photos')?></span>
                                </a>
                            </li>
                        </ul>
                        <div id="myTabContent" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
                                <div>
                                    <div id="container">
                                        <div class="view-controls-list" id="viewcontrols">
                                            <label>view :</label>
                                            <a class="gridview"><i class="glyphicon glyphicon-th"></i></a>
                                            <a class="listview active"><i class="glyphicon glyphicon-th-list"></i></a>
                                        </div>
                                        <div class="sort">
                                            <div class="sort-by">
                                                <label><?= $this->t('Sort by')?> : </label>
                                                <select>
                                                    <option value=""><?= $this->t('Most Recent')?></option>
                                                    <option value=""><?= $this->t('Price: Rs Low to High')?></option>
                                                    <option value=""><?=$this->t('Price: Rs High to Low')?></option>
                                                    <option value=""><?=$this->t('Oldest')?></option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <ul class="list">
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">There are many variations of passages of Lorem
                                                            Ipsum</h5>
                                                        <span class="adprice">R$290</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:55</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">It is a long established fact that a reader
                                                            long established</h5>
                                                        <span class="adprice">R$310</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:45</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">Contrary to popular belief, Lorem Ipsum is
                                                            not</h5>
                                                        <span class="adprice">R$190</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:30</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/no-photo.png" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">The standard chunk of Lorem Ipsum used since
                                                            the</h5>
                                                        <span class="adprice">R$480</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:25</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">Sed ut perspiciatis unde omnis iste natus
                                                            error sit voluptatem</h5>
                                                        <span class="adprice">R$859</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:24</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">But I must explain to you how all this
                                                            mistaken idea of denouncing</h5>
                                                        <span class="adprice">R$1299</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:22</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/no-photo.png" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">At vero eos et accusamus et iusto odio
                                                            dignissimos ducimus qui blanditiis</h5>
                                                        <span class="adprice">R$1099</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:21</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">On the other hand, we denounce with righteous
                                                            dislike men</h5>
                                                        <span class="adprice">R$290</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:20</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">There are many variations of passages of Lorem
                                                            Ipsum</h5>
                                                        <span class="adprice">R$899</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:05</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">ducimus qui blanditiis praesentium voluptatum
                                                            quos dolores et qua</h5>
                                                        <span class="adprice">R$199</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:04</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">There are many variations of passages of Lorem
                                                            Ipsum</h5>
                                                        <span class="adprice">R$250</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:03</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab">
                                <div>
                                    <div id="container">
                                        <div class="view-controls-list" id="viewcontrols">
                                            <label>view :</label>
                                            <a class="gridview"><i class="glyphicon glyphicon-th"></i></a>
                                            <a class="listview active"><i class="glyphicon glyphicon-th-list"></i></a>
                                        </div>
                                        <div class="sort">
                                            <div class="sort-by">
                                                <label><?= $this->t('Sort by')?> : </label>
                                                <select>
                                                    <option value=""><?= $this->t('Most Recent')?></option>
                                                    <option value=""><?= $this->t('Price: Rs Low to High')?></option>
                                                    <option value=""><?=$this->t('Price: Rs High to Low')?></option>
                                                    <option value=""><?=$this->t('Oldest')?></option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <ul class="list">
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">There are many variations of passages of Lorem
                                                            Ipsum</h5>
                                                        <span class="adprice">$290</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:55</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">It is a long established fact that a reader
                                                            long established</h5>
                                                        <span class="adprice">$310</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:45</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">Contrary to popular belief, Lorem Ipsum is
                                                            not</h5>
                                                        <span class="adprice">$190</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:30</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">The standard chunk of Lorem Ipsum used since
                                                            the</h5>
                                                        <span class="adprice">$480</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:25</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">Sed ut perspiciatis unde omnis iste natus
                                                            error sit voluptatem</h5>
                                                        <span class="adprice">$859</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:24</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">But I must explain to you how all this
                                                            mistaken idea of denouncing</h5>
                                                        <span class="adprice">$1299</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:22</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">At vero eos et accusamus et iusto odio
                                                            dignissimos ducimus qui blanditiis</h5>
                                                        <span class="adprice">$1099</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:21</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">On the other hand, we denounce with righteous
                                                            dislike men</h5>
                                                        <span class="adprice">$290</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:20</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">There are many variations of passages of Lorem
                                                            Ipsum</h5>
                                                        <span class="adprice">$899</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:05</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">ducimus qui blanditiis praesentium voluptatum
                                                            quos dolores et qua</h5>
                                                        <span class="adprice">$199</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:04</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">There are many variations of passages of Lorem
                                                            Ipsum</h5>
                                                        <span class="adprice">$250</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:03</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">who are so beguiled and demoralized by the
                                                            charms of pleasure of the moment</h5>
                                                        <span class="adprice">$189</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:03</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m2.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">you need to be sure there isn't anything
                                                            embarrassing hidden</h5>
                                                        <span class="adprice">$1090</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:03</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                            </a>
                                            <a href="<?= $this->url('ad.detail', ['slug' => 'xyz'])?>">
                                                <li>
                                                    <img src="/images/m1.jpg" title="" alt=""/>
                                                    <section class="list-left">
                                                        <h5 class="title">looked up one of the more obscure Latin
                                                            words</h5>
                                                        <span class="adprice">$599</span>
                                                        <p class="catpath"><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?> » <?= $this->t('1st Year')?></p>
                                                    </section>
                                                    <section class="list-right">
                                                        <span class="date"><?= $this->t('Today')?>, 17:02</span>
                                                        <span class="cityname"><?= $this->t('City name')?></span>
                                                    </section>
                                                    <div class="clearfix"></div>
                                                </li>
                                                <div class="clearfix"></div>
                                            </a>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <ul class="pagination pagination-sm">
                                <li><a href="#">Prev</a></li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li><a href="#">6</a></li>
                                <li><a href="#">7</a></li>
                                <li><a href="#">8</a></li>
                                <li><a href="#">Next</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
//<script>
  $(document).ready(function () {
    var elem = $('#container ul');
    $('#viewcontrols a').on('click', function (e) {
      if ($(this).hasClass('gridview')) {
        elem.fadeOut(1000, function () {
          $('#container ul').removeClass('list').addClass('grid');
          $('#viewcontrols').removeClass('view-controls-list').addClass('view-controls-grid');
          $('#viewcontrols .gridview').addClass('active');
          $('#viewcontrols .listview').removeClass('active');
          elem.fadeIn(1000);
        });
      } else if ($(this).hasClass('listview')) {
        elem.fadeOut(1000, function () {
          $('#container ul').removeClass('grid').addClass('list');
          $('#viewcontrols').removeClass('view-controls-grid').addClass('view-controls-list');
          $('#viewcontrols .gridview').removeClass('active');
          $('#viewcontrols .listview').addClass('active');
          elem.fadeIn(1000);
        });
      }
    });

    $('#slider-range').slider({
      range: true,
      min: 0,
      max: 9000,
      values: [50, 6000],
      slide: function (event, ui) {
        $('#amount').val('$' + ui.values[0] + ' - $' + ui.values[1]);
      },
    });
    $('#amount').val('$' + $('#slider-range').slider('values', 0) + ' - $' + $('#slider-range').slider('values', 1));

    var mySelect = $('#first-disabled2');

    $('#special').on('click', function () {
      mySelect.find('option:selected').prop('disabled', true);
      mySelect.selectpicker('refresh');
    });

    $('#special2').on('click', function () {
      mySelect.find('option:disabled').prop('disabled', false);
      mySelect.selectpicker('refresh');
    });

    $('#basic2').selectpicker({
      liveSearch: true,
      maxOptions: 1,
    });
  });

<?php $this->inlineScript()->captureEnd(); ?>
