<!-- breadcrumbs -->
<div class="w3layouts-breadcrumbs text-center">
    <div class="container">
        <span class="agile-breadcrumbs"><a href="<?= $this->url('home')?>"><i class="fa fa-home home_1"></i></a> / <span><?= $this->translate('Categories')?></span></span>
    </div>
</div>

<div class="categories-section main-grid-border">
    <div class="container">
        <h2 class="w3-head"><?= $this->translate('All Categories')?></h2>
        <div class="category-list">
            <div id="parentVerticalTab">
                <div class="agileits-tab_nav">
                    <ul class="resp-tabs-list hor_1">
                        <?php foreach (\App\Constants::getCategoriesDescriptions() as $slug => $description):?>
                            <li><?= $this->translate($description)?></li>
                        <?php endforeach;?>
                    </ul>
                    <a class="w3ls-ads" href="<?= $this->url('ads.list')?>"><?= $this->t('View all Ads')?></a>
                </div>
                <div class="resp-tabs-container hor_1">
                    <div>
                        <div class="category">
                            <div class="category-img">
                                <img src="/images/cat7.png" title="image" alt="" />
                            </div>
                            <div class="category-info">
                                <h4><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_EDUCACAO_INFANTIL))?></h4>
                                <span>5,12,850 Ads</span>
                                <a href="<?= $this->url('ads.list', [], ['category' => \App\Constants::CATEGORY_EDUCACAO_INFANTIL])?>"><?= $this->t('View all Ads')?></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="sub-categories">
                            <ul>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => \App\Constants::CATEGORY_EDUCACAO_INFANTIL])?>"><?= $this->t('Children Education')?></a></li>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => '1-ano'])?>"><?= $this->t('1st Year')?></a></li>
                            </ul>
                        </div>
                    </div>
                    <div>
                        <div class="category">
                            <div class="category-img">
                                <img src="/images/cat7.png" title="image" alt="" />
                            </div>
                            <div class="category-info">
                                <h4><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_FUNDAMENTAL_I))?></h4>
                                <span>2,12,850 Ads</span>
                                <a href="<?= $this->url('ads.list', [], ['category' => \App\Constants::CATEGORY_FUNDAMENTAL_I])?>"><?= $this->t('View all Ads')?></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="sub-categories">
                            <ul>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => '2-ano'])?>"><?= $this->t('2nd Year')?></a></li>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => '3-ano'])?>"><?= $this->t('3rd Year')?></a></li>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => '4-ano'])?>"><?= $this->t('4th Year')?></a></li>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => '5-ano'])?>"><?= $this->t('5th Year')?></a></li>
                            </ul>
                        </div>
                    </div>
                    <div>
                        <div class="category">
                            <div class="category-img">
                                <img src="/images/cat7.png" title="image" alt="" />
                            </div>
                            <div class="category-info">
                                <h4><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_FUNDAMENTAL_II))?></h4>
                                <span>850 Ads</span>
                                <a href="<?= $this->url('ads.list', [], ['category' => \App\Constants::CATEGORY_FUNDAMENTAL_II])?>"><?= $this->t('View all Ads')?></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="sub-categories">
                            <ul>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => '6-ano'])?>"><?= $this->t('6th Year')?></a></li>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => '7-ano'])?>"><?= $this->t('7th Year')?></a></li>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => '8-ano'])?>"><?= $this->t('8th Year')?></a></li>
                            </ul>
                        </div>
                    </div>
                    <div>
                        <div class="category">
                            <div class="category-img">
                                <img src="/images/cat7.png" title="image" alt="" />
                            </div>
                            <div class="category-info">
                                <h4><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_ENSINO_MEDIO))?></h4>
                                <span>2,12,850 Ads</span>
                                <a href="<?= $this->url('ads.list', [], ['category' => \App\Constants::CATEGORY_ENSINO_MEDIO])?>"><?= $this->t('View all Ads')?></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="sub-categories">
                            <ul>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => '9-ano'])?>"><?= $this->t('9th Year')?></a></li>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => 'em-1-ano'])?>"><?= $this->t('1st Year High School')?></a></li>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => 'em-2-ano'])?>"><?= $this->t('2nd Year High School')?></a></li>
                                <li><a href="<?= $this->url('ads.list', [], ['category' => 'em-3-ano'])?>"><?= $this->t('3rd Year High School')?></a></li>
                            </ul>
                        </div>
                    </div>
                    <div>
                        <div class="category">
                            <div class="category-img">
                                <img src="/images/cat7.png" title="image" alt="" />
                            </div>
                            <div class="category-info">
                                <h4><?= $this->t(App\Constants::categoryName(App\Constants::CATEGORY_EJA))?></h4>
                                <span>2,12,850 Ads</span>
                                <a href="<?= $this->url('ads.list', [], ['category' => \App\Constants::CATEGORY_EJA])?>"><?= $this->t('View all Ads')?></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<?php $this->inlineScript()->captureStart(); ?>
//<script>
  $(document).ready(function() {
    //Vertical Tab
    $('#parentVerticalTab').easyResponsiveTabs({
      type: 'vertical', //Types: default, vertical, accordion
      width: 'auto', //auto or any width like 600px
      fit: true, // 100% fit in a container
      closed: 'accordion', // Start closed if in accordion view
      tabidentify: 'hor_1', // The tab groups identifier
      activate: function(event) { // Callback function if tab is switched
        var $tab = $(this);
        var $info = $('#nested-tabInfo2');
        var $name = $('span', $info);
        $name.text($tab.text());
        $info.show();
      }
    });
  });
<?php $this->inlineScript()->captureEnd(); ?>
