<?php

use App\Constants;

$this->headLink()
    ->appendStylesheet('/css/bootstrap.min.css')
    ->appendStylesheet('/css/bootstrap-select.css')
    ->appendStylesheet('/css/style.css', 'all')
    ->appendStylesheet('/css/flexslider.css', 'screen')
    ->appendStylesheet('/css/font-awesome.min.css')
    ->appendStylesheet('/css/menu_sideslide.css', 'all')
    ->appendStylesheet('//fonts.googleapis.com/css?family=Ubuntu+Condensed')
    ->appendStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic')
    ->appendStylesheet('/css/jquery.uls.css')
    ->appendStylesheet('/css/jquery.uls.grid.css')
    ->appendStylesheet('/css/jquery.uls.lcd.css')
    ->appendStylesheet('/css/easy-responsive-tabs.css')
    ->appendStylesheet('/css/jquery-ui1.css');

//    <!-- Source -->
$this->headScript()
    //navigation
    ->appendFile('/js/jquery.min.js')
    ->appendFile('/js/jquery-ui.js')
    ->appendFile('/js/bootstrap.js')
    ->appendFile('/js/bootstrap-select.js')
    ->appendFile('/js/jquery.leanModal.min.js')
    ->appendFile('/js/jquery.uls.data.js')
    ->appendFile('/js/jquery.uls.data.utils.js')
    ->appendFile('/js/jquery.uls.lcd.js')
    ->appendFile('/js/jquery.uls.languagefilter.js')
    ->appendFile('/js/jquery.uls.regionfilter.js')
    ->appendFile('/js/jquery.uls.core.js')
    ->appendFile('/js/jquery.flexisel.js')
    ->appendFile('/js/responsiveslides.min.js')
    ->appendFile('/js/easyResponsiveTabs.js');

$this->inlineScript()
    ->appendFile('/js/move-top.js')
    ->appendFile('/js/easing.js')
    ->appendFile('/js/main.js')
    ->appendFile('/js/classie.js')
    ->appendFile('/js/tabs.js');
?>
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="keywords" content="Encontre um livro, livro didático, anúncios, doação livros"/>
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico"/>
    <?= $this->headTitle('Encontre um Livro')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
    <?= $this->headStyle() ?>
    <script type="application/x-javascript"> addEventListener('load', function () { setTimeout(hideURLbar, 0); }, false);

      function hideURLbar () { window.scrollTo(0, 1); } </script>
</head>
<body>
<!-- Navigation -->
<div class="agiletopbar">
    <div class="wthreenavigation">
        <div class="menu-wrap">
            <nav class="menu">
                <div class="icon-list">
                    <a href="<?= $this->url('ads.category', ['category' => Constants::CATEGORY_EDUCACAO_INFANTIL]); ?>"><i
                                class="fa fa-fw fa-book"></i><span><?= $this->translate('Children Education'); ?></span></a>
                    <a href="<?= $this->url('ads.category', ['category' => Constants::CATEGORY_FUNDAMENTAL_I]) ?>"><i
                                class="fa fa-fw fa-book"></i><span><?= $this->translate('Elementary School I'); ?></span></a>
                    <a href="<?= $this->url('ads.category', ['category' => Constants::CATEGORY_FUNDAMENTAL_II]) ?>"><i
                                class="fa fa-fw fa-book"></i><span><?= $this->translate('Elementary School II'); ?></span></a>
                    <a href="<?= $this->url('ads.category', ['category' => Constants::CATEGORY_ENSINO_MEDIO]) ?>"><i
                                class="fa fa-fw fa-book"></i><span><?= $this->translate('High School'); ?></span></a>
                    <a href="<?= $this->url('ads.category', ['category' => Constants::CATEGORY_EJA]) ?>"><i
                                class="fa fa-fw fa-book"></i><span><?= $this->translate('EJA'); ?></span></a>
                </div>
            </nav>
            <button class="close-button" id="close-button"><?= $this->translate('Close menu')?></button>
        </div>
        <button class="menu-button" id="open-button"></button>
    </div>
    <div class="clearfix"></div>
</div>
<!-- //Navigation -->

<header>
    <div class="w3ls-header"><!--header-one-->
        <div class="w3ls-header-right">
            <ul>
                <li class="dropdown head-dpdn">
                    <a href="<?= $this->url('authentication.login');?>" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i> <?= $this->translate('Sign In')?></a>
                </li>
                <li class="dropdown head-dpdn">
                    <a href="help.html"><i class="fa fa-question-circle" aria-hidden="true"></i> <?= $this->translate('Help')?></a>
                </li>
                <li class="dropdown head-dpdn">
                    <a href="#"><span class="active uls-trigger"><i class="fa fa-language" aria-hidden="true"></i><?= $this->translate('languages')?></span></a>
                </li>
                <li class="dropdown head-dpdn">
                    <div class="header-right">
                        <!-- Large modal -->
                        <div class="agile-its-selectregion">
                            <button class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                                <i class="fa fa-globe" aria-hidden="true"></i><?= $this->translate('Select City');?>
                            </button>
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
                                 aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                                &times;
                                            </button>
                                            <h4 class="modal-title" id="myModalLabel">
                                                Please Choose Your Location</h4>
                                        </div>
                                        <div class="modal-body">
                                            <form class="form-horizontal" action="#" method="get">
                                                <div class="form-group">
                                                    <select id="basic2" class="show-tick form-control" multiple>
                                                        <optgroup label="Popular Cities">
                                                            <option selected style="display:none;color:#eee;">Select
                                                                City
                                                            </option>
                                                            <option>Birmingham</option>
                                                            <option>Anchorage</option>
                                                            <option>Phoenix</option>
                                                            <option>Little Rock</option>
                                                            <option>Los Angeles</option>
                                                            <option>Denver</option>
                                                            <option>Bridgeport</option>
                                                            <option>Wilmington</option>
                                                            <option>Jacksonville</option>
                                                            <option>Atlanta</option>
                                                            <option>Honolulu</option>
                                                            <option>Boise</option>
                                                            <option>Chicago</option>
                                                            <option>Indianapolis</option>
                                                        </optgroup>
                                                        <optgroup label="Alabama">
                                                            <option>Birmingham</option>
                                                            <option>Montgomery</option>
                                                            <option>Mobile</option>
                                                            <option>Huntsville</option>
                                                            <option>Tuscaloosa</option>
                                                        </optgroup>
                                                        <optgroup label="Alaska">
                                                            <option>Anchorage</option>
                                                            <option>Fairbanks</option>
                                                            <option>Juneau</option>
                                                            <option>Sitka</option>
                                                            <option>Ketchikan</option>
                                                        </optgroup>
                                                        <optgroup label="Arizona">
                                                            <option>Phoenix</option>
                                                            <option>Tucson</option>
                                                            <option>Mesa</option>
                                                            <option>Chandler</option>
                                                            <option>Glendale</option>
                                                        </optgroup>
                                                        <optgroup label="Arkansas">
                                                            <option>Little Rock</option>
                                                            <option>Fort Smith</option>
                                                            <option>Fayetteville</option>
                                                            <option>Springdale</option>
                                                            <option>Jonesboro</option>
                                                        </optgroup>
                                                        <optgroup label="California">
                                                            <option>Los Angeles</option>
                                                            <option>San Diego</option>
                                                            <option>San Jose</option>
                                                            <option>San Francisco</option>
                                                            <option>Fresno</option>
                                                        </optgroup>
                                                        <optgroup label="Colorado">
                                                            <option>Denver</option>
                                                            <option>Colorado</option>
                                                            <option>Aurora</option>
                                                            <option>Fort Collins</option>
                                                            <option>Lakewood</option>
                                                        </optgroup>
                                                        <optgroup label="Connecticut">
                                                            <option>Bridgeport</option>
                                                            <option>New Haven</option>
                                                            <option>Hartford</option>
                                                            <option>Stamford</option>
                                                            <option>Waterbury</option>
                                                        </optgroup>
                                                        <optgroup label="Delaware">
                                                            <option>Wilmington</option>
                                                            <option>Dover</option>
                                                            <option>Newark</option>
                                                            <option>Bear</option>
                                                            <option>Middletown</option>
                                                        </optgroup>
                                                        <optgroup label="Florida">
                                                            <option>Jacksonville</option>
                                                            <option>Miami</option>
                                                            <option>Tampa</option>
                                                            <option>St. Petersburg</option>
                                                            <option>Orlando</option>
                                                        </optgroup>
                                                        <optgroup label="Georgia">
                                                            <option>Atlanta</option>
                                                            <option>Augusta</option>
                                                            <option>Columbus</option>
                                                            <option>Savannah</option>
                                                            <option>Athens</option>
                                                        </optgroup>
                                                        <optgroup label="Hawaii">
                                                            <option>Honolulu</option>
                                                            <option>Pearl City</option>
                                                            <option>Hilo</option>
                                                            <option>Kailua</option>
                                                            <option>Waipahu</option>
                                                        </optgroup>
                                                        <optgroup label="Idaho">
                                                            <option>Boise</option>
                                                            <option>Nampa</option>
                                                            <option>Meridian</option>
                                                            <option>Idaho Falls</option>
                                                            <option>Pocatello</option>
                                                        </optgroup>
                                                        <optgroup label="Illinois">
                                                            <option>Chicago</option>
                                                            <option>Aurora</option>
                                                            <option>Rockford</option>
                                                            <option>Joliet</option>
                                                            <option>Naperville</option>
                                                        </optgroup>
                                                        <optgroup label="Indiana">
                                                            <option>Indianapolis</option>
                                                            <option>Fort Wayne</option>
                                                            <option>Evansville</option>
                                                            <option>South Bend</option>
                                                            <option>Hammond</option>
                                                        </optgroup>
                                                        <optgroup label="Iowa">
                                                            <option>Des Moines</option>
                                                            <option>Cedar Rapids</option>
                                                            <option>Davenport</option>
                                                            <option>Sioux City</option>
                                                            <option>Waterloo</option>
                                                        </optgroup>
                                                        <optgroup label="Kansas">
                                                            <option>Wichita</option>
                                                            <option>Overland Park</option>
                                                            <option>Kansas City</option>
                                                            <option>Topeka</option>
                                                            <option>Olathe</option>
                                                        </optgroup>
                                                        <optgroup label="Kentucky">
                                                            <option>Louisville</option>
                                                            <option>Lexington</option>
                                                            <option>Bowling Green</option>
                                                            <option>Owensboro</option>
                                                            <option>Covington</option>
                                                        </optgroup>
                                                        <optgroup label="Louisiana">
                                                            <option>New Orleans</option>
                                                            <option>Baton Rouge</option>
                                                            <option>Shreveport</option>
                                                            <option>Metairie</option>
                                                            <option>Lafayette</option>
                                                        </optgroup>
                                                        <optgroup label="Maine">
                                                            <option>Portland</option>
                                                            <option>Lewiston</option>
                                                            <option>Bangor</option>
                                                            <option>South Portland</option>
                                                            <option>Auburn</option>
                                                        </optgroup>
                                                        <optgroup label="Maryland">
                                                            <option>Baltimore</option>
                                                            <option>Frederick</option>
                                                            <option>Rockville</option>
                                                            <option>Gaithersburg</option>
                                                            <option>Bowie</option>
                                                        </optgroup>
                                                        <optgroup label="Massachusetts">
                                                            <option>Boston</option>
                                                            <option>Worcester</option>
                                                            <option>Springfield</option>
                                                            <option>Lowell</option>
                                                            <option>Cambridge</option>
                                                        </optgroup>
                                                        <optgroup label="Michigan">
                                                            <option>Detroit</option>
                                                            <option>Grand Rapids</option>
                                                            <option>Warren</option>
                                                            <option>Sterling Heights</option>
                                                            <option>Lansing</option>
                                                        </optgroup>
                                                        <optgroup label="Minnesota">
                                                            <option>Minneapolis</option>
                                                            <option>St. Paul</option>
                                                            <option>Rochester</option>
                                                            <option>Duluth</option>
                                                            <option>Bloomington</option>
                                                        </optgroup>
                                                        <optgroup label="Mississippi">
                                                            <option>Jackson</option>
                                                            <option>Gulfport</option>
                                                            <option>Southaven</option>
                                                            <option>Hattiesburg</option>
                                                            <option>Biloxi</option>
                                                        </optgroup>
                                                        <optgroup label="Missouri">
                                                            <option>Kansas City</option>
                                                            <option>St. Louis</option>
                                                            <option>Springfield</option>
                                                            <option>Independence</option>
                                                            <option>Columbia</option>
                                                        </optgroup>
                                                        <optgroup label="Montana">
                                                            <option>Billings</option>
                                                            <option>Missoula</option>
                                                            <option>Great Falls</option>
                                                            <option>Bozeman</option>
                                                            <option>Butte-Silver Bow</option>
                                                        </optgroup>
                                                        <optgroup label="Nebraska">
                                                            <option>Omaha</option>
                                                            <option>Lincoln</option>
                                                            <option>Bellevue</option>
                                                            <option>Grand Island</option>
                                                            <option>Kearney</option>
                                                        </optgroup>
                                                        <optgroup label="Nevada">
                                                            <option>Las Vegas</option>
                                                            <option>Henderson</option>
                                                            <option>North Las Vegas</option>
                                                            <option>Reno</option>
                                                            <option>Sunrise Manor</option>
                                                        </optgroup>
                                                        <optgroup label="New Hampshire">
                                                            <option>Manchesters</option>
                                                            <option>Nashua</option>
                                                            <option>Concord</option>
                                                            <option>Dover</option>
                                                            <option>Rochester</option>
                                                        </optgroup>
                                                        <optgroup label="New Jersey">
                                                            <option>Newark</option>
                                                            <option>Jersey City</option>
                                                            <option>Paterson</option>
                                                            <option>Elizabeth</option>
                                                            <option>Edison</option>
                                                        </optgroup>
                                                        <optgroup label="New Mexico">
                                                            <option>Albuquerque</option>
                                                            <option>Las Cruces</option>
                                                            <option>Rio Rancho</option>
                                                            <option>Santa Fe</option>
                                                            <option>Roswell</option>
                                                        </optgroup>
                                                        <optgroup label="New York">
                                                            <option>New York</option>
                                                            <option>Buffalo</option>
                                                            <option>Rochester</option>
                                                            <option>Yonkers</option>
                                                            <option>Syracuse</option>
                                                        </optgroup>
                                                        <optgroup label="North Carolina">
                                                            <option>Charlotte</option>
                                                            <option>Raleigh</option>
                                                            <option>Greensboro</option>
                                                            <option>Winston-Salem</option>
                                                            <option>Durham</option>
                                                        </optgroup>
                                                        <optgroup label="North Dakota">
                                                            <option>Fargo</option>
                                                            <option>Bismarck</option>
                                                            <option>Grand Forks</option>
                                                            <option>Minot</option>
                                                            <option>West Fargo</option>
                                                        </optgroup>
                                                        <optgroup label="Ohio">
                                                            <option>Columbus</option>
                                                            <option>Cleveland</option>
                                                            <option>Cincinnati</option>
                                                            <option>Toledo</option>
                                                            <option>Akron</option>
                                                        </optgroup>
                                                        <optgroup label="Oklahoma">
                                                            <option>Oklahoma City</option>
                                                            <option>Tulsa</option>
                                                            <option>Norman</option>
                                                            <option>Broken Arrow</option>
                                                            <option>Lawton</option>
                                                        </optgroup>
                                                        <optgroup label="Oregon">
                                                            <option>Portland</option>
                                                            <option>Eugene</option>
                                                            <option>Salem</option>
                                                            <option>Gresham</option>
                                                            <option>Hillsboro</option>
                                                        </optgroup>
                                                        <optgroup label="Pennsylvania">
                                                            <option>Philadelphia</option>
                                                            <option>Pittsburgh</option>
                                                            <option>Allentown</option>
                                                            <option>Erie</option>
                                                            <option>Reading</option>
                                                        </optgroup>
                                                        <optgroup label="Rhode Island">
                                                            <option>Providence</option>
                                                            <option>Warwick</option>
                                                            <option>Cranston</option>
                                                            <option>Pawtucket</option>
                                                            <option>East Providence</option>
                                                        </optgroup>
                                                        <optgroup label="South Carolina">
                                                            <option>Columbia</option>
                                                            <option>Charleston</option>
                                                            <option>North Charleston</option>
                                                            <option>Mount Pleasant</option>
                                                            <option>Rock Hill</option>
                                                        </optgroup>
                                                        <optgroup label="South Dakota">
                                                            <option>Sioux Falls</option>
                                                            <option>Rapid City</option>
                                                            <option>Aberdeen</option>
                                                            <option>Brookings</option>
                                                            <option>Watertown</option>
                                                        </optgroup>
                                                        <optgroup label="Tennessee">
                                                            <option>Memphis</option>
                                                            <option>Nashville</option>
                                                            <option>Knoxville</option>
                                                            <option>Chattanooga</option>
                                                            <option>Clarksville</option>
                                                        </optgroup>
                                                        <optgroup label="Texas">
                                                            <option>Houston</option>
                                                            <option>San Antonio</option>
                                                            <option>Dallas</option>
                                                            <option>Austin</option>
                                                            <option>Fort Worth</option>
                                                        </optgroup>
                                                        <optgroup label="Utah">
                                                            <option>Salt Lake City</option>
                                                            <option>West Valley City</option>
                                                            <option>Provo</option>
                                                            <option>West Jordan</option>
                                                            <option>Orem</option>
                                                        </optgroup>
                                                        <optgroup label="Vermont">
                                                            <option>Burlington</option>
                                                            <option>Essex</option>
                                                            <option>South Burlington</option>
                                                            <option>Colchester</option>
                                                            <option>Rutland</option>
                                                        </optgroup>
                                                        <optgroup label="Virginia">
                                                            <option>Virginia Beach</option>
                                                            <option>Norfolk</option>
                                                            <option>Chesapeake</option>
                                                            <option>Arlington</option>
                                                            <option>Richmond</option>
                                                        </optgroup>
                                                        <optgroup label="Washington">
                                                            <option>Seattle</option>
                                                            <option>Spokane</option>
                                                            <option>Tacoma</option>
                                                            <option>Vancouver</option>
                                                            <option>Bellevue</option>
                                                        </optgroup>
                                                        <optgroup label="West Virginia">
                                                            <option>Charleston</option>
                                                            <option>Huntington</option>
                                                            <option>Parkersburg</option>
                                                            <option>Morgantown</option>
                                                            <option>Wheeling</option>
                                                        </optgroup>
                                                        <optgroup label="Wisconsin">
                                                            <option>Milwaukee</option>
                                                            <option>Madison</option>
                                                            <option>Green Bay</option>
                                                            <option>Kenosha</option>
                                                            <option>Racine</option>
                                                        </optgroup>
                                                        <optgroup label="Wyoming">
                                                            <option>Cheyenne</option>
                                                            <option>Casper</option>
                                                            <option>Laramie</option>
                                                            <option>Gillette</option>
                                                            <option>Rock Springs</option>
                                                        </optgroup>
                                                    </select>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>

        <div class="clearfix"></div>
    </div>
    <div class="container">
        <div class="agile-its-header">
            <div class="logo">
                <h1><a href="<?= $this->url('home')?>"><span>Encontre</span>UmLivro</a></h1>
            </div>
            <div class="agileits_search">
                <form action="/search" id="formSearch" method="query">
                    <input name="q" type="text" placeholder="<?= $this->translate('How can we help you today?');?>" required=""/>
                    <select id="agileinfo_search" name="cat">
                        <option value=""><?= $this->translate('All Categories');?></option>
                        <option value="<?= Constants::CATEGORY_EDUCACAO_INFANTIL?>"><?= $this->translate(Constants::categoryName(Constants::CATEGORY_EDUCACAO_INFANTIL));?></option>
                        <option value="<?= Constants::CATEGORY_FUNDAMENTAL_I?>"><?= $this->translate(Constants::categoryName(Constants::CATEGORY_FUNDAMENTAL_I));?></option>
                        <option value="<?= Constants::CATEGORY_FUNDAMENTAL_II?>"><?= $this->translate(Constants::categoryName(Constants::CATEGORY_FUNDAMENTAL_II));?></option>
                        <option value="<?= Constants::CATEGORY_ENSINO_MEDIO?>"><?= $this->translate(Constants::categoryName(Constants::CATEGORY_ENSINO_MEDIO));?></option>
                        <option value="<?= Constants::CATEGORY_EJA?>"><?= $this->translate(Constants::categoryName(Constants::CATEGORY_EJA));?></option>
                    </select>
                    <button type="submit" id="searchButton" class="btn btn-default" aria-label="Left Align">
                        <i class="fa fa-search" aria-hidden="true"> </i>
                    </button>
                </form>
                <a class="post-w3layouts-ad" href="<?= $this->url('ads.new')?>"><?= $this->translate('Post Free Ad');?></a>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</header>

<?= $this->content ?>

<!--footer section start-->
<footer>
    <div class="w3-agileits-footer-top">
        <div class="container">
            <div class="wthree-foo-grids">
                <div class="col-md-3 wthree-footer-grid">
                    <h4 class="footer-head"><?= $this->t('Who We Are');?></h4>
                    <p><?= $this->t('It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.');?></p>
                    <p><?= $this->t('The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to using Content here.')?></p>
                </div>
                <div class="col-md-3 wthree-footer-grid">
                    <h4 class="footer-head"><?= $this->translate('Help');?></h4>
                    <ul>
                        <li><a href="<?= $this->url('home');?>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i><?= $this->t('How it Works')?></a></li>
                        <li><a href="<?= $this->url('home');?>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Sitemap</a></li>
                        <li><a href="<?= $this->url('home');?>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Faq</a></li>
                        <li><a href="<?= $this->url('home');?>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Feedback</a></li>
                        <li><a href="<?= $this->url('home');?>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i><?= $this->t('Contact')?></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3 wthree-footer-grid">
                    <h4 class="footer-head"><?= $this->t('Information')?></h4>
                    <ul>
                        <li><a href="<?= $this->url('home');?>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i><?= $this->t('Locations Map')?></a></li>
                        <li><a href="<?= $this->url('home');?>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i><?= $this->t('Terms of Use')?></a></li>
                        <li><a href="<?= $this->url('home');?>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i><?= $this->t('Popular searches')?></a></li>
                        <li><a href="<?= $this->url('home');?>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i><?= $this->t('Privacy Policy')?></a></li>
                    </ul>
                </div>
                <div class="col-md-3 wthree-footer-grid">
                    <h4 class="footer-head"><?= $this->t('Contact Us');?></h4>
                    <span class="hq"><?= $this->t('Our headquarters');?></span>
                    <address>
                        <ul class="location">
                            <li><span class="glyphicon glyphicon-map-marker"></span></li>
                            <li>ZYX - 118287</li>
                        </ul>
                        <div class="clearfix"></div>
                        <ul class="location">
                            <li><span class="glyphicon glyphicon-earphone"></span></li>
                            <li>+0 561 111 235</li>
                        </ul>
                        <div class="clearfix"></div>
                        <ul class="location">
                            <li><span class="glyphicon glyphicon-envelope"></span></li>
                            <li><a href="mailto:info@example.com">mail@example.com</a></li>
                        </ul>
                    </address>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="agileits-footer-bottom text-center">
        <div class="container">
            <div class="w3-footer-logo">
                <h1><a href="<?= $this->url('home')?>"><span>Encontre</span>UmLivro</a></h1>
            </div>
            <div class="w3-footer-social-icons">
                <ul>
                    <li><a class="facebook" href="#"><i class="fa fa-facebook"
                                                        aria-hidden="true"></i><span>Facebook</span></a></li>
                    <li><a class="twitter" href="#"><i class="fa fa-twitter" aria-hidden="true"></i><span>Twitter</span></a>
                    </li>
                    <li><a class="flickr" href="#"><i class="fa fa-flickr"
                                                      aria-hidden="true"></i><span>Flickr</span></a></li>
                    <li><a class="googleplus" href="#"><i class="fa fa-google-plus"
                                                          aria-hidden="true"></i><span>Google+</span></a></li>
                    <li><a class="dribbble" href="#"><i class="fa fa-dribbble"
                                                        aria-hidden="true"></i><span>Dribbble</span></a></li>
                </ul>
            </div>
            <div class="copyrights">
                <p> © 2021 Encontre Um Livro. All Rights Reserved | Created with <i class="fa fa-heart"></i></p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</footer>
<!--footer section end-->

<?= $this->inlineScript() ?>
<script>
  $(function () {
    $('#slider').responsiveSlides({
      auto: true,
      pager: false,
      nav: true,
      speed: 500,
      maxwidth: 800,
      namespace: 'large-btns',
    });

    $('.uls-trigger').uls({
      onSelect: function (language) {
        const languageName = $.uls.data.getAutonym(language);
        $('.uls-trigger').text(languageName);
        const replacer = {'en': 'en_US', 'pt-br': 'pt_BR'};
        window.location.href = '<?= $this->url('change-language');?>/' + (replacer[language] || 'en_US');
      },
      quickList: ['en', 'pt-br'],
    });

    $('#flexiselDemo3').flexisel({
      visibleItems: 1,
      animationSpeed: 1000,
      autoPlay: true,
      autoPlaySpeed: 5000,
      pauseOnHover: true,
      enableResponsiveBreakpoints: true,
      responsiveBreakpoints: {
        portrait: {
          changePoint: 480,
          visibleItems: 1,
        },
        landscape: {
          changePoint: 640,
          visibleItems: 1,
        },
        tablet: {
          changePoint: 768,
          visibleItems: 1,
        },
      },
    });

    $().UItoTop({easingType: 'easeOutQuart'});

    $('.scroll').click(function (event) {
      event.preventDefault();
      $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1000);
    });
  });
</script>
</body>
</html>
