<?php $this->headTitle('Home'); ?>

<!-- Slider -->
<div class="slider">
    <ul class="rslides" id="slider">
        <li>
            <div class="w3ls-slide-text">
                <h3><?= $this->translate('Sell or Donate books online')?></h3>
                <a href="<?= $this->url('ads.category', ['category' => 'all'])?>" class="w3layouts-explore-all"><?= $this->translate('Browse all Categories')?></a>
            </div>
        </li>
        <li>
            <div class="w3ls-slide-text">
                <h3><?= $this->translate('Find the Best Deals Here')?></h3>
                <a href="<?= $this->url('ads.category', ['category' => 'all'])?>" class="w3layouts-explore"><?= $this->translate('Explore')?></a>
            </div>
        </li>
    </ul>
</div>
<!-- //Slider -->
<!-- content-starts-here -->
<div class="main-content">
    <div class="w3-categories">
        <h3><?= $this->translate('Browse Categories');?></h3>
        <div class="container">
            <?php foreach (\App\Constants::getCategoriesDescriptions() as  $slug => $description):?>
                <div class="col-md-3">
                    <div class="focus-grid w3layouts-boder1">
                        <a class="btn-8" href="<?= $this->url('ads.category', ['category' => $slug])?>">
                            <div class="focus-border">
                                <div class="focus-layout">
                                    <div class="focus-image"><i class="fa fa-book"></i></div>
                                    <h4 class="clrchg"><?= $this->translate($description)?></h4>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            <?php endforeach;?>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="trending-ads">
        <div class="container">
            <!-- slider -->
            <div class="agile-trend-ads">
                <h2><?= $this->translate('Trending Ads')?></h2>
                <ul id="flexiselDemo3">
                    <li>
                        <div class="col-md-3 biseller-column">
                            <a href="<?= $this->url('ad.detail', ['slug' => 'sample-ad']);?>">
                                <img src="/images/p1.jpg" alt=""/>
                                <span class="price">R$ 45</span>
                            </a>
                            <div class="w3-ad-info">
                                <h5>Lorem Ipsum is simply dummy</h5>
                                <span>1 hour ago</span>
                            </div>
                        </div>
                        <div class="col-md-3 biseller-column">
                            <a href="<?= $this->url('ad.detail', ['slug' => 'sample-ad']);?>">
                                <img src="/images/p2.jpg" alt=""/>
                                <span class="price">R$ 39</span>
                            </a>
                            <div class="w3-ad-info">
                                <h5>Lorem Ipsum is simply dummy</h5>
                                <span>3 hour ago</span>
                            </div>
                        </div>
                        <div class="col-md-3 biseller-column">
                            <a href="<?= $this->url('ad.detail', ['slug' => 'sample-ad']);?>">
                                <img src="/images/p3.jpg" alt=""/>
                                <span class="price">R$ 19</span>
                            </a>
                            <div class="w3-ad-info">
                                <h5>It is a long established fact that a reader</h5>
                                <span>8 hour ago</span>
                            </div>
                        </div>
                        <div class="col-md-3 biseller-column">
                            <a href="<?= $this->url('ad.detail', ['slug' => 'sample-ad']);?>">
                                <img src="/images/p4.jpg" alt=""/>
                                <span class="price">R$ 15</span>
                            </a>
                            <div class="w3-ad-info">
                                <h5>passage of Lorem Ipsum you need to be</h5>
                                <span>19 hour ago</span>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="col-md-3 biseller-column">
                            <a href="<?= $this->url('ad.detail', ['slug' => 'sample-ad']);?>">
                                <img src="/images/p5.jpg" alt=""/>
                                <span class="price">R$ 159</span>
                            </a>
                            <div class="w3-ad-info">
                                <h5>There are many variations of passages</h5>
                                <span>1 hour ago</span>
                            </div>
                        </div>
                        <div class="col-md-3 biseller-column">
                            <a href="<?= $this->url('ad.detail', ['slug' => 'sample-ad']);?>">
                                <img src="/images/p3.jpg" alt=""/>
                                <span class="price">R$ 109</span>
                            </a>
                            <div class="w3-ad-info">
                                <h5>passage of Lorem Ipsum you need to be</h5>
                                <span>1 day ago</span>
                            </div>
                        </div>
                        <div class="col-md-3 biseller-column">
                            <a href="<?= $this->url('ad.detail', ['slug' => 'sample-ad']);?>">
                                <img src="/images/p1.jpg" alt=""/>
                                <span class="price">R$ 10</span>
                            </a>
                            <div class="w3-ad-info">
                                <h5>It is a long established fact that a reader</h5>
                                <span>9 hour ago</span>
                            </div>
                        </div>
                        <div class="col-md-3 biseller-column">
                            <a href="<?= $this->url('ad.detail', ['slug' => 'sample-ad']);?>">
                                <img src="/images/p1.jpg" alt=""/>
                                <span class="price">R$ 18</span>
                            </a>
                            <div class="w3-ad-info">
                                <h5>Lorem Ipsum is simply dummy</h5>
                                <span>3 hour ago</span>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- //slider -->
    </div>
    <!--partners-->
    <div class="w3layouts-partners">
        <h3><?= $this->translate('Our Partners')?></h3>
        <div class="container">
            <ul>
                <li><a href="#"><img class="img-responsive" src="/images/p-1.png" alt=""></a></li>
                <li><a href="#"><img class="img-responsive" src="/images/p-2.png" alt=""></a></li>
                <li><a href="#"><img class="img-responsive" src="/images/p-3.png" alt=""></a></li>
                <li><a href="#"><img class="img-responsive" src="/images/p-4.png" alt=""></a></li>
                <li><a href="#"><img class="img-responsive" src="/images/p-5.png" alt=""></a></li>
                <li><a href="#"><img class="img-responsive" src="/images/p-6.png" alt=""></a></li>
                <li><a href="#"><img class="img-responsive" src="/images/p-7.png" alt=""></a></li>
                <li><a href="#"><img class="img-responsive" src="/images/p-8.png" alt=""></a></li>
                <li><a href="#"><img class="img-responsive" src="/images/p-9.png" alt=""></a></li>
                <li><a href="#"><img class="img-responsive" src="/images/p-10.png" alt=""></a></li>
            </ul>
        </div>
    </div>
    <!--//partners-->
    <!-- mobile app -->
    <div class="agile-info-mobile-app">
        <div class="container">
            <div class="col-md-5 w3-app-left">
                <a href="mobileapp.html"><img src="/images/app.png" alt=""></a>
            </div>
            <div class="col-md-7 w3-app-right">
                <h3><?= $this->translate('Encontre Um Livro is the <span>Easiest</span> way for Selling and buying books')?></h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor Sed bibendum varius euismod.
                    Integer eget turpis sit amet lorem rutrum ullamcorper sed sed dui. vestibulum odio at elementum.
                    Suspendisse et condimentum nibh.</p>
                <div class="agileits-dwld-app">
                    <h6><?= $this->translate('Download The App')?> :
                        <a href="#"><i class="fa fa-apple"></i></a>
                        <a href="#"><i class="fa fa-windows"></i></a>
                        <a href="#"><i class="fa fa-android"></i></a>
                    </h6>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <!-- //mobile app -->
</div>
<!--footer section start-->
