<section>
    <div id="agileits-sign-in-page" class="sign-in-wrapper">
        <div class="agileinfo_signin">
            <h3><?= $this->t('Sign Up') ?></h3>
            <form method="post">
                <input type="text" name="Name" placeholder="<?= $this->t('Your Name'); ?>" required="">
                <input type="email" name="Email" placeholder="<?= $this->t('Your Email'); ?>" required="">
                <input type="tel" name="tel" placeholder="Mobile" required="">
                <input type="password" name="Password" placeholder="<?= $this->t('Password'); ?>" required="">
                <input type="password" name="Password" placeholder="<?= $this->t('Confirm password'); ?>" required="">
                <div class="signin-rit">
						<span class="agree-checkbox">
							<label class="checkbox"><input type="checkbox"
                                                           name="checkbox"><?= $this->t('I agree to your') ?> <a
                                        class="w3layouts-t" href="terms.html"
                                        target="_blank"><?= $this->t('Terms of Use'); ?></a> <?= $this->t('and'); ?> <a
                                        class="w3layouts-t" href="privacy.html"
                                        target="_blank"><?= $this->t('Privacy Policy'); ?></a></label>
						</span>
                </div>
                <input type="submit" value="<?= $this->t('Sign Up') ?>">
            </form>
        </div>
    </div>
</section>
